name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.14.0'

    - name: Install dependencies
      run: npm install

    - name: Build Angular Project
      run: |
        export NODE_OPTIONS=--max_old_space_size=4096
        ng build --source-map=false --optimization=true

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/BookMYBook_Client/
          git pull origin master --force
          npm install
          export NODE_OPTIONS=--max_old_space_size=4096
          ng build --prod --source-map=false --optimization=true
